###
post http://localhost:5000/user/create
Content-Type: application/json

{
    "name": "red",
    "email": "red@gmail.com",
    "username": "red",
    "password": "red",
    "contact": 1231231231
}

###
post http://localhost:5000/user/get
Content-Type: application/json

{
    "username": "red",
    "password": "red"
}

###
get http://localhost:5000/watch/get

###

get http://localhost:5000/women/get